### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jayantanth** [tienfuc/gdcmdtools#89]
Traceback (most recent call last):
  File "/usr/local/bin/gdmkdir.py", line 10, in <module>
    from gdcmdtools.mkdir import GDMkdir
  File "/usr/local/lib/python2.7/dist-packages/gdcmdtools/mkdir.py", line 19, in <module>
    from gdcmdtools.base import GDBase
  File "/usr/local/lib/python2.7/dist-packages/gdcmdtools/base.py", line 7, in <module>
    from apiclient.discovery import build
  File "/usr/local/lib/python2.7/dist-packages/apiclient/__init__.py", line 1, in <module>
    from .base import APIClient, APIClient_SharedSecret
  File "/usr/local/lib/python2.7/dist-packages/apiclient/base.py", line 3, in <module>
    from urllib3 import connection_from_url
ImportError: No module named urllib3

**Comment by tienfuc** [comment]
Hi jayantanth,
How do you install gdcmdtools?
Could you try to install requests? It should fix your problem.
$ sudo pip install requests
